const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const RefundSchema = new Schema(
  {
    id: String,
    object: String,
    amount: Number,
    amount_captured: Number,
    amount_refunded: Number,
    application: String,
    application_fee: String,
    application_fee_amount: String,
    balance_transaction: String,
    billing_details: {
      address: {
        city: String,
        country: String,
        line1: String,
        line2: String,
        postal_code: String,
        state: String,
      },
      email: { type: String, default: '' },
      // email: {
      //   type: String,
      //   // required: true,
      //   // unique: true,
      //   // trim: true,
      // },
      name: String,
      phone: String,
    },
    calculated_statement_descriptor: String,
    captured: Boolean,
    currency: String,
    customer: String,
    description: String,
    destination: String,
    dispute: String,
    disputed: String,
    failure_balance_transaction: String,
    failure_code: String,
    failure_message: String,
    fraud_details: Object,
    invoice: String,
    livemode: Boolean,
    metadata: Object,
    on_behalf_of: String,
    order: String,
    outcome: {
      network_status: String,
      reason: String,
      risk_level: String,
      risk_score: Number,
      seller_message: String,
      type: String,
    },
    paid: { type: Boolean, default: false },
    payment_intent: String,
    payment_method: String,
    payment_method_details: {
      card: {
        brand: String,
        checks: {
          address_line1_check: String,
          address_postal_code_check: String,
          cvc_check: String,
        },
        country: String,
        exp_month: Number,
        exp_year: Number,
        fingerprint: String,
        funding: String,
        installments: String,
        last4: String,
        mandate: String,
        network: String,
        three_d_secure: String,
        wallet: String,
      },
      type: String,
    },
    receipt_email: String,
    receipt_number: String,
    receipt_url: String,
    refunded: Boolean,
    refunds: {
      object: String,
      data: Array,
      has_more: Boolean,
      total_count: Number,
      url: String,
    },
    review: String,
    shipping: {
      address: {
        city: String,
        country: String,
        line1: String,
        line2: String,
        postal_code: String,
        state: String,
      },
      carrier: String,
      name: String,
      phone: String,
      tracking_number: String,
    },
    source: String,
    source_transfer: String,
    statement_descriptor: String,
    statement_descriptor_suffix: String,
    status: String,
    transfer_data: String,
    transfer_group: String,
  },
  { timestamps: true },
);

module.exports = mongoose.model('Refund', RefundSchema);
